### ISSUE TITLE
Mod is dead？

### ISSUE THREAD

**Issue by mgdgfbhevdyeh** [SMEZ1234/EnhancedBiomes#7]

**Comment by mgdgfbhevdyeh** [comment]
Too bad this mod seems to be dead.

**Comment by mgdgfbhevdyeh** [comment]
@SMEZ1234 Mod is dead？

**Comment by SMEZ1234** [comment]
Pretty much. I don't have the time to maintain it anymore, as much as I might like to.

**Comment by 963548217** [comment]
@SMEZ1234 no!plssssssssssssssssssssssssssssssssupdate!

**Comment by mgdgfbhevdyeh** [comment]
If you have enough time you will maintain them?@SMEZ1234

**Comment by mgdgfbhevdyeh** [comment]
@SMEZ1234 
Hello,it's me again
I know you don't have the time
but i hope no give up
because have so many players like your mod
Minecraft's biomes mods is now less and less
I do not want to see more Biomes Mod dead
Although Tech Mod is more interesting
But I think more terrain will give players a better feel and feel
Steve is an explorer
He should not only be limited to those science and technology and a small amount of Biomes Mod Mod
Finally, I hope you do not give up
Update it,Allowing the player to feel more natural taste
pls!
